#pragma once
#include <stdio.h>
#include <memory.h>
#include <math.h>
#include <list>
#include <GL\glew.h>
#include <GL\glut.h>
#include <GLM\glm.hpp>
#include <GLM\gtc\matrix_transform.hpp>
#include <GLM\gtc\quaternion.hpp>
#include <GLM\gtc\type_ptr.hpp>

class GameTime;
class Camera;
class NewtonianPhysics;
class Node;
class SceneManager;
class ShaderManager;
class TextureManager;
class InputManager;
//class BoundingBox;
class GameObject;
class Terrain;
class SkyBox;
class Car;
class Wheel;
class Crate;

#include "GameTime.h"
#include "Camera.h" 
#include "NewtonianPhysics.h"
#include "Node.h"
#include "SceneManager.h"
#include "ShaderManager.h"
#include "InputManager.h"
#include "TextureManager.h"
//#include "BoundingBox.h"
#include "GameObject.h"
#include "Terrain.h"
#include "Skybox.h"
#include "Car.h"
#include "Wheel.h"
#include "Crate.h"